In [30]:
import pickle
import pandas as pd
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

In [2]:
pd.set_option('display.max_columns', None)

## Load data

In [3]:
with open('wamex_close_coords_to_shp_minedex_sample_5000.pickle', 'rb') as file:
    close_coords_indicies = pickle.load(file)

In [4]:
len(close_coords_indicies)

19861

In [5]:
wamex_rc = pd.read_csv('~/Desktop/CITS5553/CriticalMinerals/data/WAMEX_1_Rockchip_Original.csv')
wamex_rc.head()

/Users/zhengyuchen/opt/anaconda3/envs/cits4012/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3441: DtypeWarning: Columns (18) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,OBJECTID,DATASET,SAMPLEID,GSWANO,EXTRACT_DA,BATCH_NO,QMAPID,DLAT,DLONG,EASTING,NORTHING,RELIABILIT,SAMPLETYPE,LITHNAME,SITENO,SITEID,ORIGNAME,WAMEX_A_NO,COMPSAMPID,Ag_ppm,Al_ppm,Al2O3_pct,As_ppm,Au_ppm,B_ppm,Ba_ppm,BaO_ppm,Be_ppm,Bi_ppm,Br_ppm,C_ppm,Ca_ppm,CaO_pct,Cd_ppm,Ce_ppm,CeO2_ppm,Cl_ppm,Co_ppm,CO2_pct,Cr_ppm,Cr2O3_ppm,Cs_ppm,Cs2O_ppm,Cu_ppm,Dy_ppm,Dy2O3_ppm,Er_ppm,Er2O3_ppm,Eu_ppm,Eu2O3_ppm,F_ppm,Fe_ppm,Fe2O3_pct,Fe2O3T_pct,FeO_pct,Ga_ppm,Ga2O3_ppm,Gd_ppm,Gd2O3_ppm,Ge_ppm,H2Oneg_pct,H2Opos_pct,Hf_ppm,Hg_ppm,Ho_ppm,Ho2O3_ppm,I_ppm,In_ppm,Ir_ppb,K_ppm,K2O_pct,La_ppm,La2O3_ppm,LABnegNR_N,Li_ppm,Li2O_ppm,LOI_pct,Lu_ppm,Lu2O3_ppm,Mg_ppm,MgO_pct,Mn_ppm,MnO_pct,Mo_ppm,Na_ppm,Na2O_pct,Nb_ppm,Nb2O5_ppm,Nd_ppm,Nd2O3_ppm,Ni_ppm,Os_ppb,P_ppm,P2O5_pct,Pb_ppm,Pd_ppb,Pr_ppm,Pr2O3_ppm,Pt_ppb,Rb_ppm,Rb2O_ppm,Re_ppm,Rh_ppb,Ru_ppb,S_pct,Sb_ppm,Sb2O5_ppm,Sc_ppm,Se_ppm,Si_ppm,SiO2_pct,Sm_ppm,Sm2O3_ppm,Sn_ppm,SO3_pct,Sr_ppm,SrO_ppm,Ta_ppm,Ta2O5_ppm,Tb_ppm,Tb2O3_ppm,Te_ppm,Th_ppm,ThO2_ppm,Ti_ppm,TiO2_pct,Tl_ppm,Tm_ppm,Tm2O3_ppm,U_ppm,U3O8_ppm,V_ppm,V2O5_ppm,W_ppm,WO3_ppm,Y_ppm,Y2O3_ppm,Yb_ppm,Yb2O3_ppm,Zn_ppm,ZnO_ppm,Zr_ppm,ZrO2_ppm
0,1,NaN,229866,NaN,NaN,NaN,NaN,-34.048839,118.176663,NaN,NaN,NaN,ROCKC,NaN,NaN,NaN,NaN,70894,HMR 052,-9999.0,-9999.0,-9999.0,0.0,0.008,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,252.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999.0,-9999,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,14.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0
1,2,NaN,229867,NaN,NaN,NaN,NaN,-34.048839,118.176663,NaN,NaN,NaN,ROCKC,NaN,NaN,NaN,NaN,70894,HMR 053,-9999.0,-9999.0,-9999.0,43.0,0.012,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,447.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999.0,-9999,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,18.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0
2,3,NaN,229868,NaN,NaN,NaN,NaN,-34.048839,118.176663,NaN,NaN,NaN,ROCKC,NaN,NaN,NaN,NaN,70894,HMR 054,-9999.0,-9999.0,-9999.0,21.0,0.005,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,314.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999.0,-9999,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,28.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0
3,4,NaN,229869,NaN,NaN,NaN,NaN,-34.048839,118.176663,NaN,NaN,NaN,ROCKC,NaN,NaN,NaN,NaN,70894,HMR 055,-9999.0,-9999.0,-9999.0,13.0,0.005,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,115.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999.0,-9999,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,41.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0
4,5,NaN,229870,NaN,NaN,NaN,NaN,-34.048839,118.176663,NaN,NaN,NaN,ROCKC,NaN,NaN,NaN,NaN,70894,HMR 056,-9999.0,-9999.0,-9999.0,0.0,0.009,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,11.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999.0,-9999,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,5.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0

In [9]:
wamex = wamex_rc.iloc[close_coords_indicies,:]
wamex.shape

(19861, 143)

In [10]:
wamex.columns.values

array(['OBJECTID', 'DATASET', 'SAMPLEID', 'GSWANO', 'EXTRACT_DA',
       'BATCH_NO', 'QMAPID', 'DLAT', 'DLONG', 'EASTING', 'NORTHING',
       'RELIABILIT', 'SAMPLETYPE', 'LITHNAME', 'SITENO', 'SITEID',
       'ORIGNAME', 'WAMEX_A_NO', 'COMPSAMPID', 'Ag_ppm', 'Al_ppm',
       'Al2O3_pct', 'As_ppm', 'Au_ppm', 'B_ppm', 'Ba_ppm', 'BaO_ppm',
       'Be_ppm', 'Bi_ppm', 'Br_ppm', 'C_ppm', 'Ca_ppm', 'CaO_pct',
       'Cd_ppm', 'Ce_ppm', 'CeO2_ppm', 'Cl_ppm', 'Co_ppm', 'CO2_pct',
       'Cr_ppm', 'Cr2O3_ppm', 'Cs_ppm', 'Cs2O_ppm', 'Cu_ppm', 'Dy_ppm',
       'Dy2O3_ppm', 'Er_ppm', 'Er2O3_ppm', 'Eu_ppm', 'Eu2O3_ppm', 'F_ppm',
       'Fe_ppm', 'Fe2O3_pct', 'Fe2O3T_pct', 'FeO_pct', 'Ga_ppm',
       'Ga2O3_ppm', 'Gd_ppm', 'Gd2O3_ppm', 'Ge_ppm', 'H2Oneg_pct',
       'H2Opos_pct', 'Hf_ppm', 'Hg_ppm', 'Ho_ppm', 'Ho2O3_ppm', 'I_ppm',
       'In_ppm', 'Ir_ppb', 'K_ppm', 'K2O_pct', 'La_ppm', 'La2O3_ppm',
       'LABnegNR_N', 'Li_ppm', 'Li2O_ppm', 'LOI_pct', 'Lu_ppm',
       'Lu2O3_ppm', 'Mg_ppm', 'MgO_pct', 'Mn_ppm', 'MnO_pct', 'Mo_ppm',
       'Na_ppm', 'Na2O_pct', 'Nb_ppm', 'Nb2O5_ppm', 'Nd_ppm', 'Nd2O3_ppm',
       'Ni_ppm', 'Os_ppb', 'P_ppm', 'P2O5_pct', 'Pb_ppm', 'Pd_ppb',
       'Pr_ppm', 'Pr2O3_ppm', 'Pt_ppb', 'Rb_ppm', 'Rb2O_ppm', 'Re_ppm',
       'Rh_ppb', 'Ru_ppb', 'S_pct', 'Sb_ppm', 'Sb2O5_ppm', 'Sc_ppm',
       'Se_ppm', 'Si_ppm', 'SiO2_pct', 'Sm_ppm', 'Sm2O3_ppm', 'Sn_ppm',
       'SO3_pct', 'Sr_ppm', 'SrO_ppm', 'Ta_ppm', 'Ta2O5_ppm', 'Tb_ppm',
       'Tb2O3_ppm', 'Te_ppm', 'Th_ppm', 'ThO2_ppm', 'Ti_ppm', 'TiO2_pct',
       'Tl_ppm', 'Tm_ppm', 'Tm2O3_ppm', 'U_ppm', 'U3O8_ppm', 'V_ppm',
       'V2O5_ppm', 'W_ppm', 'WO3_ppm', 'Y_ppm', 'Y2O3_ppm', 'Yb_ppm',
       'Yb2O3_ppm', 'Zn_ppm', 'ZnO_ppm', 'Zr_ppm', 'ZrO2_ppm'],
      dtype=object)

In [11]:
new_cols = []
for col in wamex.columns: 
    if "ppm" in col:
        new_cols.append(col.split('_')[0])
    else:
        new_cols.append(col)

wamex.columns = new_cols

In [13]:
# most common pair in MINEDEX data.
abdundant_minerals = ['Copper', 'Nickel']
critical_mineral = ['Cobalt']

full_to_atomic = {
    "Copper": "Cu",
    "Cobalt": "Co",
    "Nickel": "Ni"
}

In [14]:
minerals = abdundant_minerals + critical_mineral

minerals_atomic = [full_to_atomic[mineral] for mineral in minerals]
minerals_atomic

['Cu', 'Ni', 'Co']

In [15]:
input_cols = ['DLAT', 'DLONG'] + minerals_atomic
df = wamex[input_cols]
df.head(5)

          DLAT       DLONG     Cu    Ni      Co
214 -22.525787  117.600395   15.0   6.0 -9999.0
482 -27.306604  121.417061   18.0  63.0     4.0
482 -27.306604  121.417061   18.0  63.0     4.0
482 -27.306604  121.417061   18.0  63.0     4.0
312 -22.507577  117.690084  177.0  85.0 -9999.0

## Data Cleaning

In [16]:
def replace_neg9999(val):
    if val == -9999: 
        return 0
    else:
        return val
    
    
def abs_halve_neg_val(val):
#     print(val)
    if val < 0: 
        return abs(val) / 2
    else: 
        return val

df = df.applymap(replace_neg9999)
df = df.applymap(abs_halve_neg_val)

indexs_6666 = df[df.values == -6666].index
df = df.drop(index=indexs_6666)

indexs_0 = df[df.values == 0].index
df = df.drop(index=indexs_0)

In [17]:
df = df.reset_index(drop=True)
# df = df.drop(columns=['index'])
df.head()

        DLAT       DLONG    Cu    Ni   Co
0  13.653302  121.417061  18.0  63.0  4.0
1  13.653302  121.417061  18.0  63.0  4.0
2  13.653302  121.417061  18.0  63.0  4.0
3  13.579650  121.367881  11.0   3.0  0.5
4  13.579650  121.367881  11.0   3.0  0.5

## Modeling

### DecisionTreeClassifier

In [21]:
from sklearn.model_selection import train_test_split
from sklearn import tree

In [25]:
y = df['Co']
X = df.drop(columns=['Co'])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [33]:
#Calling the Class
clf = tree.DecisionTreeClassifier()
 
#Fitting the data to the classifier
clf.fit(X_train.astype(int) , y_train.astype(int))
 
#Predict on test data
train_preds = clf.predict(X_train)
test_preds = clf.predict(X_test)

print("MSE: ", mean_squared_error(train_preds, y_train))
print("MAE: ", mean_absolute_error(train_preds, y_train))
print("R-squared:", r2_score(train_preds, y_train))
print("score of the model: ", rf.score(X_test,y_test),"\n")

MSE:  4.450039331366765
MAE:  0.40614552605703064
R-squared: 0.9929035422805903
score of the model:  1.0

### Random Forest Regression Model

In [34]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators=10, max_depth=None,min_samples_split=2, random_state=0)
rf.fit(X_train, y_train)

RandomForestRegressor(n_estimators=10, random_state=0)

In [35]:
y_rf_pred= rf.predict(X_test)
print("MSE: ", mean_squared_error(y_test,y_rf_pred))
print("MAE: ", mean_absolute_error(y_test,y_rf_pred))
print("R-squared:", r2_score(y_test,y_rf_pred))
print("score of the RF model: ", rf.score(X_test,y_test),"\n")

MSE:  1.1638317556194253e-27
MAE:  1.474131884013096e-14
R-squared: 1.0
score of the RF model:  1.0